---
title: "RADseq"
output: html_document
---

```{r setup, include=FALSE}
library(tidyr)
library(dplyr)
library(ggplot2)

knitr::opts_chunk$set(echo = TRUE)
```

# Assembly

```{bash, eval=F}
# cluster: /nas/FAC/FBM/DEE/tschwand/myrmecophilus/LTS/Assemblies/Mms_female.fa

# NCBI: SAMN42554425
```

## From

```{bash, eval=F}
mv /nas/FAC/FBM/DEE/tschwand/myrmecophilus/D2c/Assemblies/Mms_female.fa  /nas/FAC/FBM/DEE/tschwand/myrmecophilus/LTS/Assemblies
```

# HiFi reads

```{bash, eval=F}
# cluster: /nas/FAC/FBM/DEE/tschwand/myrmecophilus/LTS/Reads/HiFi/Mms_female/Mms_female.hifi.fastq.gz
# (mv /nas/FAC/FBM/DEE/tschwand/myrmecophilus/D2c/HiFi/Female/Mms_female.hifi.fastq.gz  /nas/FAC/FBM/DEE/tschwand/myrmecophilus/LTS/Reads/HiFi/Mms_female/ )
# (mv /nas/FAC/FBM/DEE/tschwand/myrmecophilus/D2c/HiFi/Female/README.md  /nas/FAC/FBM/DEE/tschwand/myrmecophilus/LTS/Reads/HiFi/Mms_female/ )

# NCBI: SRR30231907
```

## 

# WGS

```{bash, eval=F}
/nas/FAC/FBM/DEE/tschwand/myrmecophilus/LTS/Reads/SR/DNA
```

## From

Exist in two copies apparently identical on the nas but without Mms ...

```{bash, eval=F}
du -sh /nas/FAC/FBM/DEE/tschwand/myrmecophilus/D2c/SR/WGS/
#74G	/nas/FAC/FBM/DEE/tschwand/myrmecophilus/D2c/SR/WGS/
du -sh /nas/FAC/FBM/DEE/tschwand/myrmecophilus/D2c/SR/WGS/*
#114M	/nas/FAC/FBM/DEE/tschwand/myrmecophilus/D2c/SR/WGS/Downloading_NovaSeq.log
#24K	/nas/FAC/FBM/DEE/tschwand/myrmecophilus/D2c/SR/WGS/Downloading_NovaSeq.sh
#28G	/nas/FAC/FBM/DEE/tschwand/myrmecophilus/D2c/SR/WGS/Gga
#24K	/nas/FAC/FBM/DEE/tschwand/myrmecophilus/D2c/SR/WGS/Linking_Illumina.log
#24K	/nas/FAC/FBM/DEE/tschwand/myrmecophilus/D2c/SR/WGS/Linking_Illumina.sh
#22G	/nas/FAC/FBM/DEE/tschwand/myrmecophilus/D2c/SR/WGS/Mfg
#160K	/nas/FAC/FBM/DEE/tschwand/myrmecophilus/D2c/SR/WGS/Mms
#25G	/nas/FAC/FBM/DEE/tschwand/myrmecophilus/D2c/SR/WGS/Mun


du -sh /nas/FAC/FBM/DEE/tschwand/default/LTS/Myrmecophilus
#74G	/nas/FAC/FBM/DEE/tschwand/default/LTS/Myrmecophilus
du -sh /nas/FAC/FBM/DEE/tschwand/default/LTS/Myrmecophilus/*
#115M	/nas/FAC/FBM/DEE/tschwand/default/LTS/Myrmecophilus/Downloading_NovaSeq.log
#24K	/nas/FAC/FBM/DEE/tschwand/default/LTS/Myrmecophilus/Downloading_NovaSeq.sh
#27G	/nas/FAC/FBM/DEE/tschwand/default/LTS/Myrmecophilus/Gga
#24K	/nas/FAC/FBM/DEE/tschwand/default/LTS/Myrmecophilus/Linking_Illumina.log
#24K	/nas/FAC/FBM/DEE/tschwand/default/LTS/Myrmecophilus/Linking_Illumina.sh
#22G	/nas/FAC/FBM/DEE/tschwand/default/LTS/Myrmecophilus/Mfg
#160K	/nas/FAC/FBM/DEE/tschwand/default/LTS/Myrmecophilus/Mms
#25G	/nas/FAC/FBM/DEE/tschwand/default/LTS/Myrmecophilus/Mun

#It is not OK ... Mms is missing ...
##Let's recover stuff from a mix of origins ...
##Gga - OK
cp /nas/FAC/FBM/DEE/tschwand/myrmecophilus/D2c/SR/WGS/Gga/NovaSeq/* /nas/FAC/FBM/DEE/tschwand/myrmecophilus/LTS/Reads/SR/DNA/Gga #(biggest one)
##Mfg - OK
cp /nas/FAC/FBM/DEE/tschwand/default/LTS/Myrmecophilus/Mfg/NovaSeq/* /nas/FAC/FBM/DEE/tschwand/myrmecophilus/LTS/Reads/SR/DNA/ #(the one used)
mv /nas/FAC/FBM/DEE/tschwand/myrmecophilus/LTS/Reads/SR/DNA/Mfg_* /nas/FAC/FBM/DEE/tschwand/myrmecophilus/LTS/Reads/SR/DNA/Mfg
##Mms - OK
cp /work/FAC/FBM/DEE/tschwand/myrmecophilus/WGS/Reads/Mms/Raw/*fastq.gz /nas/FAC/FBM/DEE/tschwand/myrmecophilus/LTS/Reads/SR/DNA/Mms 
##Mun - OK
cp /work/FAC/FBM/DEE/tschwand/myrmecophilus/WGS/Reads/Mun/Raw/*fastq.gz /nas/FAC/FBM/DEE/tschwand/myrmecophilus/LTS/Reads/SR/DNA/Mun #(the one used)
```

## To NCBi

```{bash, eval=F}
mamba create -p /scratch/vmerel/envs/aspera
mamba activate /scratch/vmerel/envs/aspera
mamba install install rpetit3::aspera-connect

#download keyfile
mkdir -p /users/vmerel/keys
cd /users/vmerel/keys
#manual -> aspera_WGS.key

echo '#!/usr/bin/env bash

date

source ~/.bashrc
conda activate /scratch/vmerel/envs/aspera

mkdir /scratch/vmerel/ncbi_tmp_WGS
cd /scratch/vmerel/ncbi_tmp_WGS
cp /nas/FAC/FBM/DEE/tschwand/myrmecophilus/LTS/Reads/SR/DNA/Gga/*fastq.gz ./
cp /nas/FAC/FBM/DEE/tschwand/myrmecophilus/LTS/Reads/SR/DNA/Mfg/*fastq.gz ./
cp /nas/FAC/FBM/DEE/tschwand/myrmecophilus/LTS/Reads/SR/DNA/Mms/*fastq.gz ./
cp /nas/FAC/FBM/DEE/tschwand/myrmecophilus/LTS/Reads/SR/DNA/Mun/*fastq.gz ./

ascp -i /users/vmerel/keys/aspera_WGS.key -QT -l100m -k1 -d /scratch/vmerel/ncbi_tmp_WGS/ subasp@upload.ncbi.nlm.nih.gov:uploads/merel.vincent_gmail.com_Rtsqk1nS

date
' > /nas/FAC/FBM/DEE/tschwand/myrmecophilus/LTS/Reads/SR/DNA/NCBI_10122024.sh

nohup sh /nas/FAC/FBM/DEE/tschwand/myrmecophilus/LTS/Reads/SR/DNA/NCBI_10122024.sh &> /nas/FAC/FBM/DEE/tschwand/myrmecophilus/LTS/Reads/SR/DNA/NCBI_10122024.log &
 
```

du -sh 
mkdir -p /nas/FAC/FBM/DEE/tschwand/myrmecophilus/LTS/Reads/SR/DNA/
cp -r /nas/FAC/FBM/DEE/tschwand/default/LTS/Myrmecophilus 



# RADseq

NCBI BioSample attributes

```{r,eval=F}
Invertebrate.1.0 <- read.delim("~/Downloads/Invertebrate.1.0.tsv", comment.char="#")
head(Invertebrate.1.0)
#You want to fill: 
##Sample name
###Organism:

#From the sup. directly
Samples <- read.delim("~/Papers_git/rnx/Samples.csv")
head(Samples)
#You want to keep only the ones with RADseq data, and that were not filter out
Samples <- Samples %>%
  filter(radseq_seq=="TRUE")

#19.0274a should be "unknown", it is the weird gallicus
Samples$radseq_id[Samples$sample=="19.0274a"]<-"ambiguous"
#19.0248a should be "fuscus"
Samples$radseq_id[Samples$sample=="19.0248a"]<-"fuscus"

#isolate to status
Samples$status[Samples$status=="femelle"]="Female"
Samples$status[Samples$status=="larve femelle"]="Female larvae"
Samples$status[Samples$status=="larve indet"]="Larvae"
Samples$status[Samples$status=="larve male"]="Male larvae"
Samples$status[Samples$status=="male"]="Male"

summary(as.factor(Samples$host))
Samples$host[Samples$host=="indet."]="Non determined"

summary(as.factor(Samples$yyyy))
summary(as.factor(Samples$mm))

summary(as.factor(Samples$dep.))
Samples$country = ifelse(Samples$`dep.`=="Grece:", "Greece", "France:")


##For tissue

OldSamples <- read.delim("~/mse/RADseq/Myrmecophilus_samples_simon.csv") %>% select(c("ex_gri","ID"))
colnames(OldSamples) <-c("tissue","sample")
Samples <- left_join(Samples, OldSamples, by="sample")  
summary(as.factor(Samples$tissue))
Samples$tissue[Samples$tissue=="entiere"]="Whole body"
Samples$tissue[Samples$tissue=="femur"]="Leg"


###########################################################################
#You need sample name in isolate because ...
#NCBI: "Your table upload failed because multiple rows in the table (ignoring sample name, sample title and description fields) are identical. Each row must have at least one unique attribute value. Please enter information that distinguishes each sample, eg isolate names or different details of the sample collection. If the distinguishing information is in the sample name, title or description, please copy that value into the appropriate attribute, either one of the predefined attributes or a custom attribute you add. "

df <- data.frame(
  sample_name=Samples$sample,
  organism=
    paste("Myrmecophilus",
          ifelse(Samples$radseq_id %in% c("ambiguous","unknown"), "sp.", Samples$radseq_id)),
  isolate=paste(Samples$sample,Samples$status,sep="-"),
  host=Samples$host,
  collection_date=paste(Samples$yyyy,Samples$mm,sep="-"),
  geo_loc_name=paste(Samples$country,Samples$dep.,sep=" "),
  tissue=Samples$tissue
  
  )

write.table(df,"~/Desktop/ncbi_tmp/tmp.tsv", quote=F, sep="\t", row.names=F)
###########################################################################

```

NCBI SRA metadata

You can't upload raw data, NCBI want one filename per sample ...

```{r,eval=F}
OldSamples <- read.delim("~/mse/RADseq/Myrmecophilus_samples_simon.csv") %>% select(c("Plaque_myr","ID"))
colnames(OldSamples) <-c("filename","sample")
Samples <- left_join(Samples, OldSamples, by="sample")  
summary(as.factor(Samples$filename))

#filename 1: fastq
#filename 2: barcorde

#C+ 021a, 027a
Samples$barcodes=ifelse(Samples$filename %in% c("19.0021a","19.0027a"),"C+", Samples$filename)


df <- data.frame(
  sample_name=Samples$sample,
  library_ID=Samples$sample,
  title="RADseq myrmecophilus",
  library_strategy="RAD-Seq",
  library_source="GENOMIC",
  library_selection="PCR",
  library_layout="single",
  platform="ILLUMINA",
  instrument_model="Illumina HiSeq 2500",
  design_description="double-digest ddRADseq libraries following Brelsford et al. 2017",
  filetype="fastq",
  filename=paste("Myr_",Samples$filename,"_all.fastq.gz",sep=""),
  filename2=Samples$barcodes)


write.table(df,"~/Desktop/ncbi_tmp/tmp_meta.tsv", quote=F, sep="\t", row.names=F)
```

```{bash,eval=F}
```